# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a57249ebfd9289500b00d8b1096d420ffff920a0e2407577e01a640d8eb13eabfa2537e66fa71466227dd7ba024ab4244c0d4f2200d83a59ae73fa2e6beace

test:
  secret_key_base: 58e9bb6e11cd94b258bdd648e91feb2aedafa2be8cd808b3fa2b56be0300166c0f7d9343e8b302bcfbfdd0f9e46146af2b8ad47dfce820ac56125fedfba23e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
